trigger:
  branches:
    include:
    - master
  paths:
    include:
    - /src/*

resources:
  repositories:
    - repository: CentralPipeline
      type: github
      name: ToastIT-dev/CentralPipeline
      endpoint: https://github.com/ToastIT-dev/CentralPipeline.git

jobs:
- template: standard-build-template.yaml@CentralPipeline
  parameters:
    VmImage: windows-2019
    Module: PoshBot.Joker
    JobName: PoshBot_Joker_Test_Build
